version: '3.3'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample site from https://startbootstrap.com/template-overviews/agency/

services:
  centric_shop:
    build:
      context: .
      dockerfile: store.Dockerfile
    volumes:
      - .:/usr/src/app
    cap_add:
      - ALL
    depends_on:
      - psql-db
    tty: true
  psql-db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "8001:5432"
    volumes:
      - test_results:/var/lib/postgresql/data
    tty: true

volumes:
  test_results: