version: '3.3'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample site from https://startbootstrap.com/template-overviews/agency/

services:
  centric_store:
    build:
      context: .
      dockerfile: store.Dockerfile
    image: centric-store
    cap_add:
      - ALL
  psql-db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: example